import type { Metadata } from "next";
import { JsonLd, breadcrumbSchema } from "@/components/json-ld";

// /book-now is the core conversion surface — every paid-ad click lands
// here, and social shares of the URL should carry a branded card, not
// the generic sitewide fallback. OG card generated by the existing
// /api/og edge route (same pattern used on /faq, /about, /vs/*).
const ogImage =
  "https://omnileadsagi.com/api/og?" +
  "title=" + encodeURIComponent("Book a Strategy Call") +
  "&topic=" + encodeURIComponent("Free 30-minute session with Omni AI operators") +
  "&eyebrow=" + encodeURIComponent("Omni AI · Book Now");

const siteUrl = "https://omnileadsagi.com";
const pageUrl = `${siteUrl}/book-now`;

// Service JSON-LD for the free 30-min strategy call. Declaring this as a
// typed Service (not a bare WebPage) unlocks two things:
//  1. Google's Service rich result — the page can show up for "free AI
//     strategy call", "Omni AI consultation", "book AI demo" with a
//     provider/price/duration chip instead of a plain blue link.
//  2. LLM retrieval — Claude / ChatGPT / Perplexity preferentially cite
//     typed Service entities when answering "how do I talk to Omni AI?"
//     or "is there a free consultation?". Without the type, the page
//     looks like every other CTA landing page on the web.
//
// `offers.price: "0"` is the key field — the call is permanently free,
// which is also the commercial differentiator. Google's reservation /
// service rich results key off the price chip, so explicitly declaring
// $0 unlocks the "Free" badge that outperforms priced competitors in
// CTR for commercial-intent queries.
//
// provider intentionally repeats the Organization name + URL rather than
// referencing the sitewide organizationSchema by @id. Search Console's
// validator occasionally fails on cross-schema @id lookups across
// separate JSON-LD blocks; inlining the minimal provider stub is more
// resilient than relying on reference resolution.
const serviceSchema = {
  "@context": "https://schema.org",
  "@type": "Service",
  name: "Omni AI Strategy Call",
  serviceType: "AI Strategy Consultation",
  description:
    "Free 30-minute strategy session with Omni AI operators. Walk through how autonomous AI lead generation, campaigns, and operations map to your revenue target. No pitch, no credit card, no obligation.",
  provider: {
    "@type": "Organization",
    name: "Omni AI",
    url: siteUrl,
    logo: `${siteUrl}/favicon.png`,
  },
  areaServed: {
    "@type": "Place",
    name: "Worldwide",
  },
  audience: {
    "@type": "Audience",
    audienceType:
      "Solo operators, marketing agencies, and lean RevOps teams evaluating autonomous AI lead generation.",
  },
  offers: {
    "@type": "Offer",
    name: "Free Strategy Call",
    price: "0",
    priceCurrency: "USD",
    availability: "https://schema.org/InStock",
    url: pageUrl,
    description:
      "30-minute call. No credit card. No obligation. Maps autonomous AI to your revenue target.",
  },
  // aggregateRating + review pair that backs Google's star-chip rendering
  // on Service rich results. Three 5-star reviews → ratingValue 5,
  // reviewCount 3. The reviewBody strings are BYTE-FOR-BYTE the quotes
  // visible on the page body (see `/book-now/page.tsx` testimonials
  // array) — Google's review spam check cross-references schema text
  // against visible page text and suppresses the star chip on
  // mismatches, so these two must stay synchronized. If the visible
  // testimonials change, update this block in the same commit.
  aggregateRating: {
    "@type": "AggregateRating",
    ratingValue: "5",
    bestRating: "5",
    worstRating: "1",
    reviewCount: "3",
  },
  review: [
    {
      "@type": "Review",
      author: { "@type": "Person", name: "Jesse R." },
      reviewRating: { "@type": "Rating", ratingValue: "5", bestRating: "5" },
      reviewBody:
        "Showed up expecting a sales pitch, left with a full playbook for my lead pipeline. 30 free minutes turned into something I could actually run Monday morning.",
      itemReviewed: { "@type": "Service", name: "Omni AI Strategy Call" },
    },
    {
      "@type": "Review",
      author: { "@type": "Person", name: "Mia T." },
      reviewRating: { "@type": "Rating", ratingValue: "5", bestRating: "5" },
      reviewBody:
        "I've talked to four AI agencies. This was the only one where they listened before proposing anything. Ended up with a simpler, cheaper fix than what the others pushed.",
      itemReviewed: { "@type": "Service", name: "Omni AI Strategy Call" },
    },
    {
      "@type": "Review",
      author: { "@type": "Person", name: "Daniel K." },
      reviewRating: { "@type": "Rating", ratingValue: "5", bestRating: "5" },
      reviewBody:
        "Zero pressure. They asked about my business, where the bottleneck was, and gave me three concrete moves — two of which I did myself. Wasn't a pitch, was genuine help.",
      itemReviewed: { "@type": "Service", name: "Omni AI Strategy Call" },
    },
  ],
  // hasOfferCatalog — byte-aligned with the visible "What happens on
  // the call" triptych in app/book-now/page.tsx (lines 91-127). Three
  // deliverables: operator listens, operator gives advice, user leaves
  // with a plan. LLMs asked "what do I get from an Omni AI strategy
  // call?" retrieve the typed OfferCatalog here rather than trying
  // to scrape the prose. If the page triptych copy changes, update
  // this block in the same commit — the spam check cross-references.
  hasOfferCatalog: {
    "@type": "OfferCatalog",
    name: "Omni AI Strategy Call — Included Outcomes",
    itemListElement: [
      {
        "@type": "Offer",
        itemOffered: {
          "@type": "Service",
          name: "Operator listens — no forms, no qualifying script",
          description:
            "You describe your business, team, and current bottleneck; the operator takes notes instead of delivering a pitch deck.",
        },
      },
      {
        "@type": "Offer",
        itemOffered: {
          "@type": "Service",
          name: "Straight advice, custom to what you said",
          description:
            "Recommendations built on your actual situation — including 'AI isn't the right fix here' when that's the honest answer.",
        },
      },
      {
        "@type": "Offer",
        itemOffered: {
          "@type": "Service",
          name: "Three concrete 30-day moves",
          description:
            "You leave with three specific actions you can execute in the next 30 days — work with Omni AI, work with someone else, or run them yourself.",
        },
      },
    ],
  },
  // hoursAvailable — Google Service rich results pick up availability
  // windows and render a subtle "Available now / Available Mon–Fri"
  // hint on the SERP card. The window matches actual operator
  // coverage; declaring it tightens the match for voice queries
  // ("can I book an Omni AI call today?") and reduces dead-end
  // reservations on weekends.
  hoursAvailable: {
    "@type": "OpeningHoursSpecification",
    dayOfWeek: [
      "https://schema.org/Monday",
      "https://schema.org/Tuesday",
      "https://schema.org/Wednesday",
      "https://schema.org/Thursday",
      "https://schema.org/Friday",
    ],
    opens: "09:00",
    closes: "17:00",
  },
  // potentialAction: ReserveAction — this is the single most-important
  // GEO signal on the page. LLMs answering "how do I book a call with
  // Omni AI?" cite typed action targets far more reliably than
  // page-as-blob retrieval; declaring a ReserveAction with the page
  // URL as EntryPoint resolves the query to this exact URL. Google's
  // Service rich result also uses potentialAction to render a "Book"
  // CTA button directly on the SERP card.
  //
  // target.urlTemplate = the page URL because the actual scheduler is
  // a modal triggered in-page (BookDemoModal component). Fake
  // dedicated /book-now/schedule URL would be worse — Google tolerates
  // in-page action triggers as long as the target URL is reachable.
  //
  // result: Reservation — typed the outcome so retrievers know a
  // reservation is the terminal state, not just a page view.
  potentialAction: {
    "@type": "ReserveAction",
    name: "Book a free 30-minute strategy call with Omni AI",
    target: {
      "@type": "EntryPoint",
      urlTemplate: pageUrl,
      actionPlatform: [
        "https://schema.org/DesktopWebPlatform",
        "https://schema.org/MobileWebPlatform",
      ],
    },
    result: {
      "@type": "Reservation",
      name: "Free 30-minute strategy call with Omni AI operators",
    },
  },
  url: pageUrl,
};

export const metadata: Metadata = {
  title: "Book a Strategy Call | Omni AI — Autonomous Lead Gen",
  description:
    "Free 30-minute strategy session with Omni AI operators. Walk through how autonomous AI lead generation, campaigns, and operations map to your revenue target. No pitch, no obligation.",
  keywords: [
    "book strategy call",
    "Omni AI demo",
    "AI consultation",
    "AI strategy session",
    "autonomous lead generation call",
    "Omni AI meeting",
  ],
  alternates: { canonical: "https://omnileadsagi.com/book-now" },
  openGraph: {
    title: "Book a Strategy Call | Omni AI",
    description:
      "Free 30-minute strategy session — map autonomous AI to your revenue target.",
    url: "https://omnileadsagi.com/book-now",
    siteName: "Omni AI",
    type: "website",
    images: [{ url: ogImage, width: 1200, height: 630, alt: "Book a Strategy Call with Omni AI" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "Book a Strategy Call | Omni AI",
    description:
      "Free 30-minute strategy session — map autonomous AI to your revenue target.",
    images: [ogImage],
  },
};

export default function BookNowLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      {/* Service schema — unlocks Google Service rich result and gives LLMs
          a typed entity to cite for "free AI strategy call" queries. See
          the constant above for why `price: "0"` is the lever that matters
          most. */}
      <JsonLd data={serviceSchema} />
      {/* Breadcrumb schema — paired with the visible breadcrumb rendered
          at the top of the /book-now page body (added in the same cycle
          as the other marketing-page breadcrumbs). Google's breadcrumb
          rich result requires both the JSON-LD and the on-page UI;
          shipping one without the other fails the rich-result eligibility
          check. */}
      <JsonLd
        data={breadcrumbSchema([
          { name: "Home", url: siteUrl },
          { name: "Book Now", url: pageUrl },
        ])}
      />
      {children}
    </>
  );
}
