import type { Metadata } from "next";

// /book-now is the core conversion surface — every paid-ad click lands
// here, and social shares of the URL should carry a branded card, not
// the generic sitewide fallback. OG card generated by the existing
// /api/og edge route (same pattern used on /faq, /about, /vs/*).
const ogImage =
  "https://omnileadsagi.com/api/og?" +
  "title=" + encodeURIComponent("Book a Strategy Call") +
  "&topic=" + encodeURIComponent("Free 30-minute session with Omni AI operators") +
  "&eyebrow=" + encodeURIComponent("Omni AI · Book Now");

export const metadata: Metadata = {
  title: "Book a Strategy Call | Omni AI — Autonomous Lead Gen",
  description:
    "Free 30-minute strategy session with Omni AI operators. Walk through how autonomous AI lead generation, campaigns, and operations map to your revenue target. No pitch, no obligation.",
  keywords: [
    "book strategy call",
    "Omni AI demo",
    "AI consultation",
    "AI strategy session",
    "autonomous lead generation call",
    "Omni AI meeting",
  ],
  alternates: { canonical: "https://omnileadsagi.com/book-now" },
  openGraph: {
    title: "Book a Strategy Call | Omni AI",
    description:
      "Free 30-minute strategy session — map autonomous AI to your revenue target.",
    url: "https://omnileadsagi.com/book-now",
    siteName: "Omni AI",
    type: "website",
    images: [{ url: ogImage, width: 1200, height: 630, alt: "Book a Strategy Call with Omni AI" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "Book a Strategy Call | Omni AI",
    description:
      "Free 30-minute strategy session — map autonomous AI to your revenue target.",
    images: [ogImage],
  },
};

export default function BookNowLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
}
