"use client";
export const dynamic = "force-dynamic";
import { useState, useEffect, useCallback, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Shield,Lock,Eye,EyeOff,AlertTriangle,Activity,CheckCircle2,XCircle,RefreshCw,Clock,Zap,TrendingUp,Brain,Bot,Cpu,GitCommit,Server,Send,Rocket,Terminal,AlertCircle,CheckCheck,Loader2,Database,Mail } from "lucide-react";
import { useAuth } from "@/hooks/use-auth";
import { useProfile } from "@/hooks/use-profile";
interface PI{project:string;overall_score:number;build_health:number;seo_score:number;performance_score:number;backend_score:number;mobile_score:number;sessions_completed:number;total_lines_written:number;current_focus:string;next_priorities:string[];improvement_velocity:number;updated_at:string}
interface AE{id:string;project:string;commit_message:string;category:string;lines_added:number;created_at:string}
interface DP{id:string;project:string;status:string;commit_message:string;created_at:string}
interface AC{id:string;command:string;target_project:string;status:string;response:string;created_at:string;error:string}
interface VE{id:string;project:string;error_type:string;description:string;severity:string;auto_fixed:boolean}
interface HD{status:"ok"|"degraded"|"down";checks:Record<string,{ok:boolean;latency:number}>;uptime_ms:number}
const E:Record<string,string>={"omni-ai":"\u{1F9E0}",imperium:"\u{1F451}",cps:"\u{1F3E5}","omni-leads":"\u{1F4C8}",leifson:"\u{1F528}",youngs:"\u{1FA9A}"};
function tA(d:string){if(!d)return"\u2014";const ms=Date.now()-new Date(d).getTime(),m=Math.floor(ms/60000),h=Math.floor(m/60),dy=Math.floor(h/24);return dy>0?`${dy}d`:h>0?`${h}h`:m>0?`${m}m`:"now"}
function sG(s:number){if(s>=85)return{l:"A",c:"text-emerald-400"};if(s>=70)return{l:"B",c:"text-green-400"};if(s>=55)return{l:"C",c:"text-yellow-400"};if(s>=40)return{l:"D",c:"text-orange-400"};return{l:"F",c:"text-red-400"}}
const CSS=`.cc-p{border:1px solid rgba(16,185,129,.08);border-radius:12px;background:rgba(255,255,255,.01);overflow:hidden}.cc-h{padding:10px 14px;background:rgba(16,185,129,.03);border-bottom:1px solid rgba(16,185,129,.08);font-family:ui-monospace,monospace;font-size:10px;letter-spacing:.1em;color:rgba(255,255,255,.5);text-transform:uppercase}.st::-webkit-scrollbar{width:3px}.st::-webkit-scrollbar-thumb{background:rgba(16,185,129,.15);border-radius:9px}.sn::-webkit-scrollbar{display:none}`;
function LoginGate({onAuth}:{onAuth:()=>void}){const{signIn}=useAuth();const[u,sU]=useState("");const[pw,sPw]=useState("");const[sh,sSh]=useState(false);const[err,sE]=useState("");const[ld,sL]=useState(false);const[gl,sGl]=useState("COMMAND CENTER");useEffect(()=>{const ch="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789@#$%&*",t="COMMAND CENTER";let f=0;const iv=setInterval(()=>{f++;if(f>30){sGl(t);clearInterval(iv);return}sGl(t.split("").map((c,i)=>i<f/2?c:ch[Math.floor(Math.random()*ch.length)]).join(""))},50);return()=>clearInterval(iv)},[]);const go=async()=>{if(!u||!pw){sE("Credentials required");return}sL(true);sE("");const{error:e}=await signIn(u,pw);if(e){sE(e);sL(false)}else onAuth()};
return(<div className="min-h-screen bg-[#030305] flex items-center justify-center relative overflow-hidden"><div className="absolute inset-0 opacity-[0.03]" style={{backgroundImage:"linear-gradient(rgba(0,255,136,.3) 1px,transparent 1px),linear-gradient(90deg,rgba(0,255,136,.3) 1px,transparent 1px)",backgroundSize:"40px 40px"}}/><motion.div className="absolute left-0 right-0 h-[2px] bg-gradient-to-r from-transparent via-emerald-500/20 to-transparent" animate={{top:["0%","100%"]}} transition={{duration:4,repeat:Infinity,ease:"linear"}}/><div className="absolute top-6 left-6 w-16 h-16 border-l-2 border-t-2 border-emerald-500/20 rounded-tl-lg"/><div className="absolute top-6 right-6 w-16 h-16 border-r-2 border-t-2 border-emerald-500/20 rounded-tr-lg"/><div className="absolute bottom-6 left-6 w-16 h-16 border-l-2 border-b-2 border-emerald-500/20 rounded-bl-lg"/><div className="absolute bottom-6 right-6 w-16 h-16 border-r-2 border-b-2 border-emerald-500/20 rounded-br-lg"/><div className="absolute top-0 left-0 right-0 h-8 bg-emerald-500/5 border-b border-emerald-500/10 flex items-center px-4 gap-4"><span className="text-[10px] font-mono text-emerald-500/40">SYS::OMNI_AI</span><span className="text-[10px] font-mono text-emerald-500/30">|</span><span className="text-[10px] font-mono text-emerald-500/40">v4.0</span><span className="text-[10px] font-mono text-emerald-500/30">|</span><span className="text-[10px] font-mono text-emerald-500/40">SECURE</span><div className="ml-auto flex items-center gap-1.5"><span className="w-1.5 h-1.5 bg-emerald-400 rounded-full animate-pulse"/><span className="text-[10px] font-mono text-emerald-500/40">ONLINE</span></div></div>
<motion.div initial={{opacity:0,scale:.95}} animate={{opacity:1,scale:1}} className="relative z-10 w-full max-w-sm mx-4"><div className="border border-emerald-500/15 rounded-xl bg-[#050508]/90 backdrop-blur-xl overflow-hidden"><div className="h-10 bg-emerald-500/5 border-b border-emerald-500/10 flex items-center px-4 gap-2"><div className="flex gap-1.5"><div className="w-2.5 h-2.5 rounded-full bg-red-500/60"/><div className="w-2.5 h-2.5 rounded-full bg-yellow-500/60"/><div className="w-2.5 h-2.5 rounded-full bg-emerald-500/60"/></div><span className="text-[10px] font-mono text-emerald-500/50 ml-2">omni://auth</span></div><div className="p-6 space-y-6"><div className="text-center space-y-3"><motion.div className="w-16 h-16 mx-auto rounded-2xl bg-gradient-to-br from-emerald-500/20 to-cyan-500/10 border border-emerald-500/20 flex items-center justify-center" animate={{boxShadow:["0 0 20px rgba(16,185,129,0)","0 0 30px rgba(16,185,129,.15)","0 0 20px rgba(16,185,129,0)"]}} transition={{duration:3,repeat:Infinity}}><Shield className="w-8 h-8 text-emerald-400"/></motion.div><h1 className="text-lg font-mono font-bold tracking-[.2em] text-emerald-400">{gl}</h1><p className="text-[11px] font-mono text-gray-600">AUTHORIZATION REQUIRED</p></div>
<div className="space-y-3"><div className="space-y-1.5"><label className="text-[10px] font-mono text-emerald-500/50 uppercase tracking-widest">Identifier</label><input type="text" value={u} onChange={e=>sU(e.target.value)} onKeyDown={e=>e.key==="Enter"&&go()} placeholder="username" className="w-full h-10 px-3 bg-white/[.03] border border-emerald-500/10 rounded-lg text-sm font-mono text-white placeholder:text-gray-700 focus:outline-none focus:border-emerald-500/30" autoFocus/></div><div className="space-y-1.5"><label className="text-[10px] font-mono text-emerald-500/50 uppercase tracking-widest">Passkey</label><div className="relative"><input type={sh?"text":"password"} value={pw} onChange={e=>sPw(e.target.value)} onKeyDown={e=>e.key==="Enter"&&go()} placeholder="--------" className="w-full h-10 px-3 pr-10 bg-white/[.03] border border-emerald-500/10 rounded-lg text-sm font-mono text-white placeholder:text-gray-700 focus:outline-none focus:border-emerald-500/30"/><button type="button" onClick={()=>sSh(!sh)} className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-600 hover:text-emerald-400">{sh?<EyeOff className="w-4 h-4"/>:<Eye className="w-4 h-4"/>}</button></div></div></div>
<AnimatePresence>{err&&<motion.div initial={{opacity:0,height:0}} animate={{opacity:1,height:"auto"}} exit={{opacity:0,height:0}} className="flex items-center gap-2 p-2.5 rounded-lg bg-red-500/10 border border-red-500/15"><AlertTriangle className="w-3.5 h-3.5 text-red-400"/><span className="text-xs font-mono text-red-400">{err}</span></motion.div>}</AnimatePresence>
<button onClick={go} disabled={ld} className="w-full h-10 rounded-lg font-mono text-sm font-medium tracking-wider bg-gradient-to-r from-emerald-600 to-cyan-600 text-white disabled:opacity-50 flex items-center justify-center gap-2">{ld?<Loader2 className="w-4 h-4 animate-spin"/>:<><Lock className="w-3.5 h-3.5"/>AUTHENTICATE</>}</button><p className="text-center text-[9px] font-mono text-gray-700">ENCRYPTED {"\u00B7"} ADMIN ONLY</p></div></div></motion.div></div>)}
function LiveChat(){const[cmds,sC]=useState<AC[]>([]);const[inp,sI]=useState("");const[tgt,sT]=useState("all");const[snd,sS]=useState(false);const sr=useRef<HTMLDivElement>(null);const ir=useRef<HTMLInputElement>(null);const ld=useCallback(async()=>{try{const r=await fetch("/api/agents/commands?limit=50");if(r.ok)sC(await r.json())}catch{}},[]);useEffect(()=>{ld();const iv=setInterval(ld,4000);return()=>clearInterval(iv)},[ld]);useEffect(()=>{sr.current&&(sr.current.scrollTop=sr.current.scrollHeight)},[cmds]);const send=async()=>{if(!inp.trim()||snd)return;sS(true);try{await fetch("/api/agents/commands",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({command:inp.trim(),command_type:inp.startsWith("/")?"action":"chat",target_project:tgt==="all"?null:tgt})});sI("");await ld()}catch{}sS(false);ir.current?.focus()};
return(<div className="cc-p h-full flex flex-col"><div className="cc-h"><div className="flex items-center gap-2"><Terminal className="w-3.5 h-3.5 text-emerald-400"/><span>LIVE AGENT TERMINAL</span><span className="ml-auto flex items-center gap-1.5"><span className="w-1.5 h-1.5 bg-emerald-400 rounded-full animate-pulse"/><span className="text-emerald-400">LIVE</span></span></div></div><div ref={sr} className="flex-1 overflow-y-auto p-3 space-y-3 st">{cmds.length===0?<div className="h-full flex items-center justify-center"><div className="text-center space-y-2 opacity-40"><Terminal className="w-8 h-8 text-emerald-400 mx-auto"/><p className="text-xs font-mono text-gray-500">Awaiting commands...</p><p className="text-[10px] font-mono text-gray-700">&gt; &quot;Fix the hero on CPS&quot;</p></div></div>:cmds.map(c=><div key={c.id} className="space-y-1.5"><div className="flex items-start gap-2"><span className="text-emerald-500 font-mono text-xs mt-0.5">&gt;</span><div className="flex-1 min-w-0"><div className="flex items-center gap-2">{c.target_project&&<span className="text-[9px] font-mono px-1.5 py-0.5 rounded bg-emerald-500/10 text-emerald-400 border border-emerald-500/15">{E[c.target_project]||"\u{1F4E6}"} {c.target_project}</span>}<span className="text-[9px] font-mono text-gray-700 ml-auto">{new Date(c.created_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</span></div><p className="text-sm font-mono text-gray-200 mt-0.5">{c.command}</p></div></div>{(c.response||c.status==="processing")&&<div className="flex items-start gap-2 ml-4"><Bot className="w-3 h-3 text-cyan-400 mt-0.5"/><div className="flex-1 p-2 rounded-lg bg-white/[.02] border border-white/[.04]"><div className="flex items-center gap-1.5 mb-1"><span className="text-[9px] font-mono text-cyan-400">$MAFI_AGENT</span>{c.status==="pending"?<Clock className="w-3 h-3 text-yellow-400"/>:c.status==="processing"?<Loader2 className="w-3 h-3 text-cyan-400 animate-spin"/>:c.status==="completed"?<CheckCheck className="w-3 h-3 text-emerald-400"/>:<XCircle className="w-3 h-3 text-red-400"/>}</div>{c.status==="processing"?<div className="flex items-center gap-1.5"><span className="flex gap-0.5">{[0,1,2].map(i=><span key={i} className="w-1 h-1 bg-cyan-400 rounded-full animate-bounce" style={{animationDelay:`${i*.15}s`}}/>)}</span><span className="text-[11px] font-mono text-gray-600">Processing...</span></div>:<p className="text-xs font-mono text-gray-400 whitespace-pre-wrap">{c.response||"Queued"}</p>}{c.error&&<p className="text-[10px] font-mono text-red-400 mt-1">{c.error}</p>}</div></div>}</div>)}</div>
<div className="border-t border-emerald-500/10 p-3 space-y-2"><div className="flex gap-1 overflow-x-auto sn"><button onClick={()=>sT("all")} className={`px-2 py-1 rounded text-[10px] font-mono whitespace-nowrap ${tgt==="all"?"bg-emerald-500/15 text-emerald-400 border border-emerald-500/20":"text-gray-600 hover:text-gray-400"}`}>ALL</button>{Object.entries(E).map(([k,v])=><button key={k} onClick={()=>sT(k)} className={`px-2 py-1 rounded text-[10px] font-mono whitespace-nowrap ${tgt===k?"bg-emerald-500/15 text-emerald-400 border border-emerald-500/20":"text-gray-600 hover:text-gray-400"}`}>{v} {k}</button>)}</div><div className="flex gap-2"><div className="flex-1 relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-emerald-500/50 font-mono text-sm">&gt;</span><input ref={ir} value={inp} onChange={e=>sI(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Enter command..." className="w-full h-9 pl-7 pr-3 bg-white/[.03] border border-emerald-500/10 rounded-lg text-sm font-mono text-white placeholder:text-gray-700 focus:outline-none focus:border-emerald-500/30"/></div><button onClick={send} disabled={snd||!inp.trim()} className="h-9 px-4 rounded-lg bg-emerald-600 text-white font-mono text-xs hover:bg-emerald-500 disabled:opacity-30 flex items-center gap-1.5">{snd?<Loader2 className="w-3.5 h-3.5 animate-spin"/>:<Send className="w-3.5 h-3.5"/>}</button></div></div></div>}
export default function CommandCenter(){const{user,loading:aL}=useAuth();const{profileLoading:pL,isAdmin}=useProfile();const[ok,sOk]=useState(false);const[proj,sP]=useState<PI[]>([]);const[edits,sE]=useState<AE[]>([]);const[deps,sD]=useState<DP[]>([]);const[hp,sH]=useState<HD|null>(null);const[dl,sDl]=useState(true);const[ck,sCk]=useState(new Date());
useEffect(()=>{const iv=setInterval(()=>sCk(new Date()),1000);return()=>clearInterval(iv)},[]);
useEffect(()=>{if(!aL&&user&&!pL&&isAdmin)sOk(true)},[user,aL,pL,isAdmin]);
const fA=useCallback(async()=>{sDl(true);try{const[p,e,h]=await Promise.all([fetch("/api/agents/intelligence").catch(()=>null),fetch("/api/agents/edits").catch(()=>null),fetch("/api/health").catch(()=>null)]);if(p?.ok)try{sP(await p.json())}catch{};if(e?.ok)try{sE(await e.json())}catch{};if(h?.ok)try{sH(await h.json())}catch{};try{const r=await fetch("/api/agents/deployments");if(r.ok)sD(await r.json())}catch{}}catch{};sDl(false)},[]);
useEffect(()=>{if(ok){fA();const iv=setInterval(fA,20000);return()=>clearInterval(iv)}},[ok,fA]);
if(!ok)return<LoginGate onAuth={()=>sOk(true)}/>;
if(aL||pL)return<div className="min-h-screen bg-[#030305] flex items-center justify-center"><Loader2 className="w-6 h-6 text-emerald-400 animate-spin"/></div>;
if(!isAdmin)return<div className="min-h-screen bg-[#030305] flex items-center justify-center"><div className="text-center"><Lock className="w-8 h-8 text-red-400 mx-auto"/><p className="text-sm font-mono text-red-400 mt-2">ACCESS DENIED</p></div></div>;
const avg=proj.length?Math.round(proj.reduce((s,p)=>s+p.overall_score,0)/proj.length):0;const tc=edits.length;const tl=edits.reduce((s,e)=>s+(e.lines_added||0),0);
return(<div className="min-h-screen bg-[#030305] text-white relative overflow-hidden"><style>{CSS}</style><div className="absolute inset-0 opacity-[.02]" style={{backgroundImage:"linear-gradient(rgba(0,255,136,.4) 1px,transparent 1px),linear-gradient(90deg,rgba(0,255,136,.4) 1px,transparent 1px)",backgroundSize:"60px 60px"}}/><motion.div className="absolute left-0 right-0 h-px bg-gradient-to-r from-transparent via-emerald-500/10 to-transparent pointer-events-none z-50" animate={{top:["0%","100%"]}} transition={{duration:8,repeat:Infinity,ease:"linear"}}/>
<div className="sticky top-0 z-40 bg-[#030305]/90 backdrop-blur-md border-b border-emerald-500/10"><div className="max-w-[1600px] mx-auto px-4 lg:px-6 h-12 flex items-center gap-4"><div className="flex items-center gap-3"><div className="w-7 h-7 rounded-lg bg-gradient-to-br from-emerald-500/20 to-cyan-500/10 border border-emerald-500/20 flex items-center justify-center"><Terminal className="w-3.5 h-3.5 text-emerald-400"/></div><div className="hidden sm:block"><p className="text-xs font-mono font-medium text-white tracking-wider">$MAFI COMMAND CENTER</p><p className="text-[9px] font-mono text-gray-600">OMNI SYNTHETIC INTELLIGENCE v4.0</p></div><p className="sm:hidden text-xs font-mono font-medium text-white tracking-wider">$MAFI</p></div><div className="hidden md:flex items-center gap-3 ml-auto mr-auto"><div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/15"><span className="w-1.5 h-1.5 bg-emerald-400 rounded-full animate-pulse"/><span className="text-[10px] font-mono text-emerald-400">SYSTEMS NOMINAL</span></div><div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-white/[.03] border border-white/[.06]"><Brain className="w-3 h-3 text-purple-400"/><span className="text-[10px] font-mono text-gray-400">AVG {avg}/100</span></div></div><div className="flex items-center gap-3 ml-auto md:ml-0"><span className="text-xs font-mono text-emerald-400/60 tabular-nums hidden sm:block">{ck.toLocaleTimeString([],{hour12:false})}</span><button onClick={fA} disabled={dl} className="w-7 h-7 rounded-lg bg-white/[.03] border border-white/[.06] flex items-center justify-center text-gray-500 hover:text-emerald-400"><RefreshCw className={`w-3 h-3 ${dl?"animate-spin":""}`}/></button></div></div></div>
<div className="max-w-[1600px] mx-auto px-4 lg:px-6 py-4"><div className="grid grid-cols-2 sm:grid-cols-4 gap-3">{[{l:"UPTIME",v:hp?(()=>{const s=Math.floor(hp.uptime_ms/1000),m=Math.floor(s/60),h=Math.floor(m/60);return h>0?`${h}h ${m%60}m`:`${m}m`})():"\u2014",i:Clock,c:"text-blue-400",b:"border-blue-500/15"},{l:"AI SCORE",v:`${avg}/100`,i:Brain,c:"text-purple-400",b:"border-purple-500/15"},{l:"COMMITS",v:String(tc),i:GitCommit,c:"text-emerald-400",b:"border-emerald-500/15"},{l:"LINES",v:tl.toLocaleString(),i:Cpu,c:"text-yellow-400",b:"border-yellow-500/15"}].map(s=>{const I=s.i;return<div key={s.l} className={`flex items-center gap-3 p-3 rounded-xl border bg-white/[.01] ${s.b}`}><I className={`w-4 h-4 ${s.c}`}/><div><p className="text-sm font-mono font-bold text-white">{s.v}</p><p className="text-[9px] font-mono text-gray-600">{s.l}</p></div></div>})}</div></div>
<div className="max-w-[1600px] mx-auto px-4 lg:px-6 pb-12 space-y-4">
<div className="grid grid-cols-1 lg:grid-cols-2 gap-4"><div className="min-h-[400px]"><LiveChat/></div>
<div className="cc-p"><div className="cc-h"><div className="flex items-center gap-2"><Brain className="w-3.5 h-3.5 text-purple-400"/><span>SYNTHETIC INTELLIGENCE</span></div></div><div className="p-3 space-y-1.5">{proj.length===0?<p className="text-xs font-mono text-gray-600 text-center py-6">No data</p>:proj.sort((a,b)=>b.overall_score-a.overall_score).map(p=>{const g=sG(p.overall_score);return<div key={p.project} className="flex items-center gap-3 px-3 py-2.5 rounded-lg border border-white/[.04] bg-white/[.015] hover:bg-white/[.03]"><span className="text-lg">{E[p.project]||"\u{1F4E6}"}</span><div className="flex-1 min-w-0"><div className="flex items-center gap-2"><span className="text-sm font-mono font-medium text-white capitalize">{p.project}</span>{p.improvement_velocity>0&&<span className="text-[10px] font-mono text-emerald-400">+{p.improvement_velocity.toFixed(0)}</span>}</div><p className="text-[10px] font-mono text-gray-600 truncate">{p.current_focus||"Idle"}</p></div><span className={`text-2xl font-mono font-bold ${g.c}`}>{g.l}</span><span className="text-xs font-mono text-gray-500">{p.overall_score}</span></div>})}</div></div></div>
<div className="grid grid-cols-1 md:grid-cols-2 gap-4">
<div className="cc-p"><div className="cc-h"><div className="flex items-center gap-2"><Rocket className="w-3.5 h-3.5 text-orange-400"/><span>DEPLOY STATUS</span></div></div><div className="p-3 grid grid-cols-2 sm:grid-cols-3 gap-2">{Object.entries(E).map(([k,em])=>{const d=deps.find(x=>x.project===k);const lv=d?.status==="success",fl=d?.status==="failed";return<div key={k} className={`p-2.5 rounded-lg border ${lv?"border-emerald-500/15 bg-emerald-500/[.03]":fl?"border-red-500/15 bg-red-500/[.03]":"border-white/[.04] bg-white/[.015]"}`}><div className="flex items-center gap-2 mb-1"><span>{em}</span><span className="text-[11px] font-mono text-white capitalize truncate">{k}</span></div>{d?<div className="flex items-center gap-1">{lv&&<CheckCircle2 className="w-3 h-3 text-emerald-400"/>}{fl&&<XCircle className="w-3 h-3 text-red-400"/>}<span className={`text-[10px] font-mono ${lv?"text-emerald-400":"text-red-400"}`}>{lv?"LIVE":"FAILED"}</span></div>:<span className="text-[9px] font-mono text-gray-700">No deploys</span>}</div>})}</div></div>
<div className="cc-p"><div className="cc-h"><div className="flex items-center gap-2"><Server className="w-3.5 h-3.5 text-gray-400"/><span>SERVICES</span>{hp&&<span className={`ml-auto ${hp.status==="ok"?"text-emerald-400":"text-yellow-400"}`}>{hp.status==="ok"?"ALL OK":"DEGRADED"}</span>}</div></div><div className="p-3 space-y-1.5">{hp&&Object.entries(hp.checks).map(([k,c])=>{const icons:Record<string,React.ElementType>={database:Database,auth:Shield,newsletter:Mail,api:Zap};const I=icons[k]||Activity;return<div key={k} className="flex items-center gap-2.5 py-1"><span className={`w-1.5 h-1.5 rounded-full ${c.ok?"bg-emerald-400":"bg-red-400"}`}/><I className="w-3 h-3 text-gray-500"/><span className="text-[11px] font-mono text-gray-400 flex-1 uppercase">{k}</span><span className={`text-[10px] font-mono ${c.latency<200?"text-emerald-400":"text-red-400"}`}>{c.latency}ms</span></div>})}</div></div></div>
<div className="cc-p"><div className="cc-h"><div className="flex items-center gap-2"><GitCommit className="w-3.5 h-3.5 text-emerald-400"/><span>AGENT COMMITS</span><span className="ml-auto text-emerald-400">{tc}</span></div></div><div className="p-3 space-y-1.5 max-h-64 overflow-y-auto st">{edits.length===0?<p className="text-xs font-mono text-gray-600 text-center py-6">No commits</p>:edits.slice(0,20).map(e=><div key={e.id} className="flex items-start gap-2 py-1.5 border-b border-white/[.03] last:border-0"><span className="text-sm mt-0.5">{E[e.project]||"\u{1F4E6}"}</span><div className="flex-1 min-w-0"><div className="flex items-center gap-1.5"><span className="text-[9px] font-mono text-gray-400">[{e.category}]</span><span className="text-[10px] font-mono text-emerald-400 ml-auto">+{e.lines_added}</span></div><p className="text-[11px] font-mono text-gray-400 truncate">{e.commit_message}</p><p className="text-[9px] font-mono text-gray-700">{tA(e.created_at)}</p></div></div>)}</div></div>
</div>
<div className="fixed bottom-0 left-0 right-0 h-7 bg-[#030305]/95 backdrop-blur-sm border-t border-emerald-500/10 flex items-center px-4 gap-6 z-40"><span className="text-[9px] font-mono text-emerald-500/40">SYS::OMNI_INTELLIGENCE</span><span className="text-[9px] font-mono text-gray-700">|</span><span className="text-[9px] font-mono text-gray-600">{proj.length} projects</span><span className="text-[9px] font-mono text-gray-700">|</span><span className="text-[9px] font-mono text-gray-600">{deps.length} deploys</span><span className="ml-auto text-[9px] font-mono text-emerald-500/40">{ck.toLocaleDateString(undefined,{weekday:"short",month:"short",day:"numeric"})}</span></div></div>)}
