/**
 * AI CEO Briefing — daily executive briefing generated by Claude from real
 * business metrics (Supabase). Delivered to owner via Telegram + email.
 *
 * Called from the existing newsletter send cron so we stay within Vercel
 * Hobby's 2-cron limit.
 */

import type { SupabaseClient } from '@supabase/supabase-js';
import { ptStartOfDayIso, ptEndOfDayIso } from './tz';

const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY || '';
const ANTHROPIC_MODEL = process.env.ANTHROPIC_MODEL || 'claude-sonnet-4-6';
const TELEGRAM_BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN || '';
const TELEGRAM_CHAT_ID = process.env.TELEGRAM_ADMIN_CHAT_ID || process.env.TELEGRAM_CHAT_ID || '';
const RESEND_API_KEY = process.env.RESEND_API_KEY || '';
const BRIEFING_FROM = process.env.NEWSLETTER_FROM_EMAIL || 'Omni AI <newsletter@omnios.news>';
const BRIEFING_TO = process.env.NEWSLETTER_TO_EMAIL || 'sitanim8@gmail.com';

export interface BusinessMetrics {
  newSubscribers24h: number;
  unsubscribes24h: number;
  totalActiveSubscribers: number;
  premiumSubscribers: number;
  newLeads24h: number;
  totalLeads: number;
  demoBookingsToday: number;
  demoBookingsUpcoming7d: number;
  newsletterSentYesterday: boolean;
  newsletterSubject: string | null;
  newsletterRecipients: number;
  landingPagesLive: number;
  recentActivity: string[];
}

export interface CEOBriefing {
  headline: string;
  wins: string;
  risks: string;
  action: string;
}

// ── Metrics Collection ────────────────────────────────────────────────────────

export async function collectBusinessMetrics(
  supabase: SupabaseClient
): Promise<BusinessMetrics> {
  const now = new Date();
  const yesterday = new Date(now.getTime() - 24 * 60 * 60 * 1000);
  const in7d = new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000);
  // Anchor "today" on PT calendar day (not server UTC) — see lib/tz.
  const todayStart = new Date(ptStartOfDayIso(now));
  const todayEnd = new Date(ptEndOfDayIso(now));

  const metrics: BusinessMetrics = {
    newSubscribers24h: 0,
    unsubscribes24h: 0,
    totalActiveSubscribers: 0,
    premiumSubscribers: 0,
    newLeads24h: 0,
    totalLeads: 0,
    demoBookingsToday: 0,
    demoBookingsUpcoming7d: 0,
    newsletterSentYesterday: false,
    newsletterSubject: null,
    newsletterRecipients: 0,
    landingPagesLive: 0,
    recentActivity: [],
  };

  // Subscribers — snapshot
  try {
    const { data } = await supabase
      .from('newsletter_subscriptions')
      .select('subscribed, subscription_tier, created_at, updated_at');

    const rows = data || [];
    metrics.totalActiveSubscribers = rows.filter((r: any) => r.subscribed !== false).length;
    // Premium count must also exclude unsubscribed rows — otherwise
    // churned premium subscribers stayed counted in the headline
    // metric and inflated the briefing's "premium subscribers"
    // figure long after they left.
    metrics.premiumSubscribers = rows.filter(
      (r: any) => r.subscription_tier === 'premium' && r.subscribed !== false,
    ).length;
    metrics.newSubscribers24h = rows.filter(
      (r: any) => r.created_at && new Date(r.created_at) >= yesterday
    ).length;
    metrics.unsubscribes24h = rows.filter(
      (r: any) =>
        r.subscribed === false &&
        r.updated_at &&
        new Date(r.updated_at) >= yesterday
    ).length;
  } catch {}

  // Landing page leads
  try {
    const { count: total } = await supabase
      .from('landing_page_leads')
      .select('id', { count: 'exact', head: true });
    metrics.totalLeads = total || 0;

    const { count: recent } = await supabase
      .from('landing_page_leads')
      .select('id', { count: 'exact', head: true })
      .gte('created_at', yesterday.toISOString());
    metrics.newLeads24h = recent || 0;
  } catch {}

  // Demo bookings
  try {
    const { count: today } = await supabase
      .from('demo_bookings')
      .select('id', { count: 'exact', head: true })
      .gte('scheduled_at', todayStart.toISOString())
      .lte('scheduled_at', todayEnd.toISOString());
    metrics.demoBookingsToday = today || 0;

    const { count: upcoming } = await supabase
      .from('demo_bookings')
      .select('id', { count: 'exact', head: true })
      .gte('scheduled_at', todayEnd.toISOString())
      .lte('scheduled_at', in7d.toISOString());
    metrics.demoBookingsUpcoming7d = upcoming || 0;
  } catch {}

  // Yesterday's newsletter
  try {
    const { data } = await supabase
      .from('newsletter_sends')
      .select('subject, recipients_total, sent_at')
      .gte('sent_at', yesterday.toISOString())
      .order('sent_at', { ascending: false })
      .limit(1);
    if (data && data[0]) {
      metrics.newsletterSentYesterday = true;
      metrics.newsletterSubject = (data[0] as any).subject || null;
      metrics.newsletterRecipients = (data[0] as any).recipients_total || 0;
    }
  } catch {}

  // Landing pages live
  try {
    const { count } = await supabase
      .from('landing_pages')
      .select('slug', { count: 'exact', head: true });
    metrics.landingPagesLive = count || 0;
  } catch {}

  // Recent activity (last 24h, max 5 items)
  try {
    const { data } = await supabase
      .from('activity_log')
      .select('subject, type')
      .gte('created_at', yesterday.toISOString())
      .order('created_at', { ascending: false })
      .limit(5);
    metrics.recentActivity = (data || []).map((a: any) => a.subject).filter(Boolean);
  } catch {}

  return metrics;
}

// ── Claude Analysis ───────────────────────────────────────────────────────────

export async function generateCEOBriefing(
  metrics: BusinessMetrics
): Promise<CEOBriefing> {
  const fallback: CEOBriefing = {
    headline: `${metrics.totalActiveSubscribers} active subscribers · ${metrics.totalLeads} leads total`,
    wins:
      metrics.newSubscribers24h > 0
        ? `${metrics.newSubscribers24h} new subscriber${metrics.newSubscribers24h > 1 ? 's' : ''} in the last 24h.`
        : 'No new subscribers in the last 24h — pipeline is quiet.',
    risks:
      metrics.unsubscribes24h > 0
        ? `${metrics.unsubscribes24h} unsubscribe${metrics.unsubscribes24h > 1 ? 's' : ''} yesterday — watch retention.`
        : 'No immediate risks detected.',
    action:
      metrics.newLeads24h > 0
        ? `Follow up with the ${metrics.newLeads24h} new lead${metrics.newLeads24h > 1 ? 's' : ''} from landing pages today.`
        : 'Push a new trending landing page today to keep lead flow live.',
  };

  if (!ANTHROPIC_API_KEY) return fallback;

  const prompt = `You are the AI CEO of Omni AI, an AI automation agency. Your founder, Alfred, just woke up. Give him today's executive briefing based on the real business metrics below. Be direct, specific, and confident — like a chief of staff, not a dashboard.

METRICS (last 24h + current state):
- Active subscribers: ${metrics.totalActiveSubscribers} (${metrics.premiumSubscribers} premium)
- New subscribers (24h): ${metrics.newSubscribers24h}
- Unsubscribes (24h): ${metrics.unsubscribes24h}
- Total leads: ${metrics.totalLeads}
- New leads (24h): ${metrics.newLeads24h}
- Demos booked today: ${metrics.demoBookingsToday}
- Demos booked next 7d: ${metrics.demoBookingsUpcoming7d}
- Yesterday's newsletter: ${metrics.newsletterSentYesterday ? `"${metrics.newsletterSubject}" → ${metrics.newsletterRecipients} recipients` : 'not sent'}
- Landing pages live: ${metrics.landingPagesLive}
- Recent activity: ${metrics.recentActivity.length ? metrics.recentActivity.slice(0, 5).join(' | ') : 'none logged'}

Return JSON with exactly these keys (no other text):
{
  "headline": "one short punchy sentence — the single most important thing he needs to know today",
  "wins": "one or two sentences. Name specific numbers from above. If nothing went well, say so honestly.",
  "risks": "one or two sentences about what to watch. Name the specific metric. If nothing is concerning, say the pipeline is stable.",
  "action": "one decisive sentence telling him what to do today — not a list, one move"
}`;

  try {
    const res = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': ANTHROPIC_API_KEY,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: ANTHROPIC_MODEL,
        max_tokens: 600,
        messages: [{ role: 'user', content: prompt }],
      }),
    });
    if (!res.ok) return fallback;
    const json = await res.json();
    const text = json.content?.[0]?.text || '';
    const match = text.match(/\{[\s\S]*\}/);
    if (!match) return fallback;
    const parsed = JSON.parse(match[0]);
    return {
      headline: String(parsed.headline || fallback.headline),
      wins: String(parsed.wins || fallback.wins),
      risks: String(parsed.risks || fallback.risks),
      action: String(parsed.action || fallback.action),
    };
  } catch (e) {
    console.error('[CEO Briefing] Claude call failed:', e);
    return fallback;
  }
}

// ── Formatters ────────────────────────────────────────────────────────────────

function formatTelegram(metrics: BusinessMetrics, briefing: CEOBriefing): string {
  const today = new Date().toLocaleDateString('en-US', {
    timeZone: 'America/Los_Angeles',
    weekday: 'long',
    month: 'long',
    day: 'numeric',
  });

  // Telegram's Markdown parse mode treats *, _, `, [ as control chars.
  // Claude-generated headline/wins/risks/action content frequently
  // contains stray asterisks or underscores ("Q4 was *the* breakout"),
  // which used to make the API return 400 and silently drop the entire
  // briefing. Escape interpolated values; leave the literal control
  // characters in our own template untouched.
  const md = (s: string | null | undefined) =>
    (s ? String(s) : '').replace(/[*_`\[]/g, c => `\\${c}`);

  const lines: string[] = [];
  lines.push(`🧠 *AI CEO Briefing* — _${md(today)}_`);
  lines.push('');
  lines.push(`*${md(briefing.headline)}*`);
  lines.push('');
  lines.push(`✅ *Wins*`);
  lines.push(md(briefing.wins));
  lines.push('');
  lines.push(`⚠️ *Risks*`);
  lines.push(md(briefing.risks));
  lines.push('');
  lines.push(`🎯 *Today's Move*`);
  lines.push(md(briefing.action));
  lines.push('');
  lines.push(
    `_Subs ${metrics.totalActiveSubscribers} (+${metrics.newSubscribers24h}/-${metrics.unsubscribes24h}) · Leads ${metrics.totalLeads} (+${metrics.newLeads24h}) · Demos today ${metrics.demoBookingsToday}_`
  );

  return lines.join('\n');
}

function formatEmail(metrics: BusinessMetrics, briefing: CEOBriefing): string {
  const today = new Date().toLocaleDateString('en-US', {
    timeZone: 'America/Los_Angeles',
    weekday: 'long',
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  });

  return `<!doctype html>
<html>
<body style="margin:0;background:#050505;color:#e5e7eb;font-family:ui-sans-serif,system-ui,Helvetica,Arial,sans-serif;">
  <div style="max-width:560px;margin:0 auto;padding:32px 20px;">
    <div style="font-size:12px;letter-spacing:2px;color:#a78bfa;text-transform:uppercase;margin-bottom:6px;">AI CEO Briefing</div>
    <div style="font-size:13px;color:#6b7280;margin-bottom:20px;">${today}</div>

    <div style="background:linear-gradient(135deg,rgba(167,139,250,0.12),rgba(34,211,238,0.08));border:1px solid rgba(167,139,250,0.25);border-radius:14px;padding:18px 20px;margin-bottom:20px;">
      <div style="font-size:18px;font-weight:700;color:#fff;line-height:1.35;">${escapeHtml(briefing.headline)}</div>
    </div>

    <div style="margin-bottom:18px;">
      <div style="font-size:12px;letter-spacing:1px;text-transform:uppercase;color:#34d399;margin-bottom:6px;">Wins</div>
      <div style="color:#d1d5db;line-height:1.6;">${escapeHtml(briefing.wins)}</div>
    </div>

    <div style="margin-bottom:18px;">
      <div style="font-size:12px;letter-spacing:1px;text-transform:uppercase;color:#fbbf24;margin-bottom:6px;">Risks</div>
      <div style="color:#d1d5db;line-height:1.6;">${escapeHtml(briefing.risks)}</div>
    </div>

    <div style="margin-bottom:22px;">
      <div style="font-size:12px;letter-spacing:1px;text-transform:uppercase;color:#22d3ee;margin-bottom:6px;">Today&rsquo;s Move</div>
      <div style="color:#d1d5db;line-height:1.6;">${escapeHtml(briefing.action)}</div>
    </div>

    <div style="border-top:1px solid rgba(255,255,255,0.08);padding-top:16px;color:#6b7280;font-size:12px;line-height:1.7;">
      <div><strong style="color:#9ca3af;">Subscribers:</strong> ${metrics.totalActiveSubscribers} active · ${metrics.premiumSubscribers} premium · +${metrics.newSubscribers24h} / -${metrics.unsubscribes24h} (24h)</div>
      <div><strong style="color:#9ca3af;">Leads:</strong> ${metrics.totalLeads} total · +${metrics.newLeads24h} (24h)</div>
      <div><strong style="color:#9ca3af;">Demos:</strong> ${metrics.demoBookingsToday} today · ${metrics.demoBookingsUpcoming7d} in next 7 days</div>
      <div><strong style="color:#9ca3af;">Newsletter yesterday:</strong> ${metrics.newsletterSentYesterday ? `"${escapeHtml(metrics.newsletterSubject || '')}" → ${metrics.newsletterRecipients} recipients` : 'not sent'}</div>
      <div><strong style="color:#9ca3af;">Landing pages:</strong> ${metrics.landingPagesLive} live</div>
    </div>
  </div>
</body>
</html>`;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

// ── Senders ───────────────────────────────────────────────────────────────────

async function sendBriefingTelegram(text: string): Promise<boolean> {
  if (!TELEGRAM_BOT_TOKEN || !TELEGRAM_CHAT_ID) return false;
  try {
    const res = await fetch(
      `https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          chat_id: TELEGRAM_CHAT_ID,
          text,
          parse_mode: 'Markdown',
          disable_web_page_preview: true,
        }),
      }
    );
    return res.ok;
  } catch (e) {
    console.error('[CEO Briefing] Telegram send failed:', e);
    return false;
  }
}

async function sendBriefingEmail(subject: string, html: string): Promise<boolean> {
  if (!RESEND_API_KEY) return false;
  try {
    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${RESEND_API_KEY}`,
      },
      body: JSON.stringify({
        from: BRIEFING_FROM,
        to: [BRIEFING_TO],
        subject,
        html,
      }),
    });
    return res.ok;
  } catch (e) {
    console.error('[CEO Briefing] Email send failed:', e);
    return false;
  }
}

// ── Entry Point ───────────────────────────────────────────────────────────────

export async function runCEOBriefing(supabase: SupabaseClient): Promise<{
  ok: boolean;
  telegramOk: boolean;
  emailOk: boolean;
  briefing: CEOBriefing;
  metrics: BusinessMetrics;
}> {
  const metrics = await collectBusinessMetrics(supabase);
  const briefing = await generateCEOBriefing(metrics);

  const telegramText = formatTelegram(metrics, briefing);
  const emailHtml = formatEmail(metrics, briefing);
  const emailSubject = `AI CEO Briefing — ${briefing.headline}`;

  const [telegramOk, emailOk] = await Promise.all([
    sendBriefingTelegram(telegramText),
    sendBriefingEmail(emailSubject, emailHtml),
  ]);

  console.log(
    `[CEO Briefing] Telegram=${telegramOk} Email=${emailOk} Headline="${briefing.headline}"`
  );

  return { ok: telegramOk || emailOk, telegramOk, emailOk, briefing, metrics };
}
