-- Durable publication and delivery state for the Success Empire morning
-- principle and afternoon personal letter workflows.

create table if not exists public.success_empire_entries (
  id uuid primary key default gen_random_uuid(),
  publication_date date not null,
  kind text not null check (kind in ('principle', 'journal')),
  slug text not null unique
    check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  title text not null check (char_length(title) between 3 and 180),
  deck text not null check (char_length(deck) between 20 and 420),
  salutation text,
  sections jsonb not null default '[]'::jsonb
    check (jsonb_typeof(sections) = 'array'),
  closing text,
  signature text,
  principle_slug text,
  tags text[] not null default '{}'::text[],
  status text not null default 'draft'
    check (status in ('draft', 'published', 'failed')),
  published_at timestamptz,
  sender_name text not null,
  sender_email text not null,
  email_status text not null default 'pending'
    check (
      email_status in (
        'pending', 'accepted', 'delivered', 'failed', 'suppressed', 'skipped'
      )
    ),
  email_provider_id text,
  email_idempotency_key text,
  email_error text,
  telegram_status text not null default 'pending'
    check (
      telegram_status in (
        'pending', 'accepted', 'delivered', 'failed', 'skipped'
      )
    ),
  telegram_chat_id text,
  telegram_message_id bigint,
  telegram_error text,
  source_context jsonb not null default '{}'::jsonb
    check (jsonb_typeof(source_context) = 'object'),
  generation_receipt jsonb not null default '{}'::jsonb
    check (jsonb_typeof(generation_receipt) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (publication_date, kind),
  check (status <> 'published' or published_at is not null),
  check (kind <> 'journal' or principle_slug is not null)
);

create table if not exists public.success_empire_delivery_attempts (
  id bigint generated by default as identity primary key,
  entry_id uuid not null
    references public.success_empire_entries(id) on delete cascade,
  channel text not null check (channel in ('email', 'telegram')),
  idempotency_key text not null,
  status text not null
    check (
      status in (
        'pending', 'accepted', 'delivered', 'failed', 'suppressed', 'skipped'
      )
    ),
  provider_id text,
  error text,
  metadata jsonb not null default '{}'::jsonb
    check (jsonb_typeof(metadata) = 'object'),
  attempted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (channel, idempotency_key)
);

create index if not exists success_empire_entries_publication_idx
  on public.success_empire_entries (publication_date desc, kind);

create index if not exists success_empire_entries_status_idx
  on public.success_empire_entries (status, published_at desc);

create index if not exists success_empire_delivery_attempts_entry_idx
  on public.success_empire_delivery_attempts (entry_id, channel, attempted_at desc);

create or replace function public.set_success_empire_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists success_empire_entries_set_updated_at
  on public.success_empire_entries;
create trigger success_empire_entries_set_updated_at
before update on public.success_empire_entries
for each row execute function public.set_success_empire_updated_at();

drop trigger if exists success_empire_delivery_attempts_set_updated_at
  on public.success_empire_delivery_attempts;
create trigger success_empire_delivery_attempts_set_updated_at
before update on public.success_empire_delivery_attempts
for each row execute function public.set_success_empire_updated_at();

alter table public.success_empire_entries enable row level security;
alter table public.success_empire_delivery_attempts enable row level security;

revoke all on public.success_empire_entries from anon, authenticated;
revoke all on public.success_empire_delivery_attempts from anon, authenticated;

grant select on public.success_empire_entries to anon, authenticated;

drop policy if exists "Public can read published Success Empire entries"
  on public.success_empire_entries;
create policy "Public can read published Success Empire entries"
on public.success_empire_entries
for select
to anon, authenticated
using (
  status = 'published'
  and published_at is not null
  and published_at <= now()
);

comment on table public.success_empire_entries is
  'Published Success Empire morning principles and afternoon personal letters.';

comment on table public.success_empire_delivery_attempts is
  'Retryable, idempotent email and Telegram delivery receipts for Success Empire.';
